### ISSUE TITLE
Can't run stack ghci

### ISSUE THREAD

**Issue by zuzia-kru** [brynedwards/spock-tutorials#1]
Hello, I was following the tutorial from https://www.spock.li/tutorials/rest-api but sadly got stuck the first time I needed to run stack ghci.
I'm getting this error:
``` <command line>: can't load .so/.DLL for: /Users/user/.stack/snapshots/x86_64-osx/c1364315869982c449d179a0116c672c85679cd86de9e54788e182f77aa297d6/8.0.2/lib/x86_64-osx-ghc-8.0.2/libHStime-locale-compat-0.1.1.3-KZ1jqNx8uhlHjmuPPj6V1Y-ghc8.0.2.dylib..... ```
I tried all the suggestions from this issue: https://github.com/commercialhaskell/stack/issues/740
But none worked for me. Then I got the same issue by directly cloning this repo and trying to run it.
Any help would be great, I was looking forward to following this tutorial on REST APIs.

Thanks

**Comment by brynedwards** [comment]
Hi there, sorry about that, it looks like an issue with stack or the compiler itself and I don't have a Mac, I'm using Linux and it still compiles. This was written quite a while ago and hasn't been updated; you could try using a more recent version of the compiler by putting `lts-12.26` as the resolver in `stack.yaml`.

**Comment by zuzia-kru** [comment]
Hi,
Thanks for your response putting a higher version of the resolver did work. Thank you very much!
